### ISSUE TITLE
Vehicles not persistent

### ISSUE THREAD

**Issue by Awokado1** [Bob74/MMI-SP#1]
I believe you're not developing the mod anymore, perhaps you even know about the issue, but still - Simple problem, the vehicles are not persistent and they do vanish after getting away/leaving the game. A bummer, since it was an important aspect of the mod. The rest, though, seem to be working fine.

**Comment by Bob74** [comment]
Hey, I was not aware of this issue, it was basically the main goal of this mod.
I will try to grab some time to get a look at it.

Also I should release the source code (it might not be the cleanest because it was made quite a long time ago)

**Comment by Bob74** [comment]
It should be fixed now.
1.2.1 is out at https://www.gta5-mods.com/scripts/mors-mutual-insurance-single-player-mmi-sp

Thank you for your bug report!

**Comment by Bob74** [comment]
It should be fixed now.
1.2.1 is out at https://www.gta5-mods.com/scripts/mors-mutual-insurance-single-player-mmi-sp

Thank you for your bug report!
